language: node_js
node_js:
  - '8'
addons:
  postgresql: '10'
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
services:
  - postgresql
env:
  global:
    - PGPORT=5433
  matrix:
    - NODE_APP_INSTANCE=travis
before_script:
  - psql -c "CREATE DATABASE hlpugs;"
  - psql -c "CREATE USER hlpugs WITH PASSWORD 'build';"
  - psql -c "GRANT ALL PRIVILEGES ON DATABASE hlpugs TO hlpugs;"
install:
  - npm install
script:
  - npm run build-db
  - npm run build
  - npm run coverage
after_success:
  - npm run codecov