language: node_js
node_js:
  - '8'
env:
  global:
    - PGPORT=5433
  matrix:
    - NODE_APP_INSTANCE=travis
install:
  - npm install
script:
  - npm run build
  - npm run coverage
after_success:
  - npm run codecov