language: node_js
node_js:
  - '8'
addons:
  postgresql: '10'
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
services:
  - postgresql
env:
  - NODE_APP_INSTANCE=travis
install:
  - npm install
script:
  - npm run generateDB
  - npm run build
  - npm run test